schema:
  - http://localhost:8080/v1/graphql:
      headers:
        x-hasura-admin-secret: "123456"
extensions:
  endpoints:
    default:
      url: http://localhost:8080/v1/graphql
      headers:
        x-hasura-admin-secret: "123456"
